[Service]
  Port = "8001"
  Environment = "development"
[Database]
  name = "xm_exercise"
  engine = "sqlite"
  host = "localhost"
  port = "5432"
  user = "postgres"
  pass = "postgres"
  ideal = "50"