[Service]
  Environment = "development"
  ValidLocations = "India,Cyprus"
[Database]
  Name = "xm_exercise"
  Engine = "sqlite"
[JWT]
  PrivateKey="abcd"
[Admin]
  Email = "admin@xm.com"
  Pass = "admin"
